
from .dynamic_dropdown_node import NODE_CLASS_MAPPINGS as DYNAMIC_DROPDOWN_NODE_CLASS_MAPPINGS
from .dynamic_dropdown_node import NODE_DISPLAY_NAME_MAPPINGS as DYNAMIC_DROPDOWN_NODE_DISPLAY_NAME_MAPPINGS
from .if_branch_node import NODE_CLASS_MAPPINGS as IF_BRANCH_NODE_CLASS_MAPPINGS
from .if_branch_node import NODE_DISPLAY_NAME_MAPPINGS as IF_BRANCH_NODE_DISPLAY_NAME_MAPPINGS
from .test_node import NODE_CLASS_MAPPINGS as TEST_NODE_CLASS_MAPPINGS
from .test_node import NODE_DISPLAY_NAME_MAPPINGS as TEST_NODE_DISPLAY_NAME_MAPPINGS

WEB_DIRECTORY = "./web"

NODE_CLASS_MAPPINGS = {
    **DYNAMIC_DROPDOWN_NODE_CLASS_MAPPINGS,
    **IF_BRANCH_NODE_CLASS_MAPPINGS,
    **TEST_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **DYNAMIC_DROPDOWN_NODE_DISPLAY_NAME_MAPPINGS,
    **IF_BRANCH_NODE_DISPLAY_NAME_MAPPINGS,
    **TEST_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
